package qile.garden.field.entity;

import java.util.Date;

public class Field {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.fieldName
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String fieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.length
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Double length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.width
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Double width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.gardenId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer gardenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.freshId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer freshId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.price
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.amount
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.creatTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.preparedTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Date preparedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.growTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Date growTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.collectTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Date collectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.maturationTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Date maturationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.id
     *
     * @return the value of field.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.id
     *
     * @param id the value for field.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.fieldName
     *
     * @return the value of field.fieldName
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.fieldName
     *
     * @param fieldName the value for field.fieldName
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.length
     *
     * @return the value of field.length
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Double getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.length
     *
     * @param length the value for field.length
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setLength(Double length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.width
     *
     * @return the value of field.width
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Double getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.width
     *
     * @param width the value for field.width
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setWidth(Double width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.gardenId
     *
     * @return the value of field.gardenId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getGardenId() {
        return gardenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.gardenId
     *
     * @param gardenId the value for field.gardenId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setGardenId(Integer gardenId) {
        this.gardenId = gardenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.freshId
     *
     * @return the value of field.freshId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getFreshId() {
        return freshId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.freshId
     *
     * @param freshId the value for field.freshId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setFreshId(Integer freshId) {
        this.freshId = freshId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.price
     *
     * @return the value of field.price
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.price
     *
     * @param price the value for field.price
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.amount
     *
     * @return the value of field.amount
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.amount
     *
     * @param amount the value for field.amount
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.creatTime
     *
     * @return the value of field.creatTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.creatTime
     *
     * @param creatTime the value for field.creatTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.preparedTime
     *
     * @return the value of field.preparedTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Date getPreparedTime() {
        return preparedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.preparedTime
     *
     * @param preparedTime the value for field.preparedTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setPreparedTime(Date preparedTime) {
        this.preparedTime = preparedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.growTime
     *
     * @return the value of field.growTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Date getGrowTime() {
        return growTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.growTime
     *
     * @param growTime the value for field.growTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setGrowTime(Date growTime) {
        this.growTime = growTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.collectTime
     *
     * @return the value of field.collectTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.collectTime
     *
     * @param collectTime the value for field.collectTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.maturationTime
     *
     * @return the value of field.maturationTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Date getMaturationTime() {
        return maturationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.maturationTime
     *
     * @param maturationTime the value for field.maturationTime
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setMaturationTime(Date maturationTime) {
        this.maturationTime = maturationTime;
    }
}