package qile.garden.field.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FieldExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public FieldExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFieldnameIsNull() {
            addCriterion("fieldName is null");
            return (Criteria) this;
        }

        public Criteria andFieldnameIsNotNull() {
            addCriterion("fieldName is not null");
            return (Criteria) this;
        }

        public Criteria andFieldnameEqualTo(String value) {
            addCriterion("fieldName =", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameNotEqualTo(String value) {
            addCriterion("fieldName <>", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameGreaterThan(String value) {
            addCriterion("fieldName >", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameGreaterThanOrEqualTo(String value) {
            addCriterion("fieldName >=", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameLessThan(String value) {
            addCriterion("fieldName <", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameLessThanOrEqualTo(String value) {
            addCriterion("fieldName <=", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameLike(String value) {
            addCriterion("fieldName like", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameNotLike(String value) {
            addCriterion("fieldName not like", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameIn(List<String> values) {
            addCriterion("fieldName in", values, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameNotIn(List<String> values) {
            addCriterion("fieldName not in", values, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameBetween(String value1, String value2) {
            addCriterion("fieldName between", value1, value2, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameNotBetween(String value1, String value2) {
            addCriterion("fieldName not between", value1, value2, "fieldname");
            return (Criteria) this;
        }

        public Criteria andLengthIsNull() {
            addCriterion("length is null");
            return (Criteria) this;
        }

        public Criteria andLengthIsNotNull() {
            addCriterion("length is not null");
            return (Criteria) this;
        }

        public Criteria andLengthEqualTo(Double value) {
            addCriterion("length =", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotEqualTo(Double value) {
            addCriterion("length <>", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThan(Double value) {
            addCriterion("length >", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThanOrEqualTo(Double value) {
            addCriterion("length >=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThan(Double value) {
            addCriterion("length <", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThanOrEqualTo(Double value) {
            addCriterion("length <=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthIn(List<Double> values) {
            addCriterion("length in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotIn(List<Double> values) {
            addCriterion("length not in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthBetween(Double value1, Double value2) {
            addCriterion("length between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotBetween(Double value1, Double value2) {
            addCriterion("length not between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Double value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Double value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Double value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Double value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Double value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Double value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Double> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Double> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Double value1, Double value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Double value1, Double value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andGardenidIsNull() {
            addCriterion("gardenId is null");
            return (Criteria) this;
        }

        public Criteria andGardenidIsNotNull() {
            addCriterion("gardenId is not null");
            return (Criteria) this;
        }

        public Criteria andGardenidEqualTo(Integer value) {
            addCriterion("gardenId =", value, "gardenid");
            return (Criteria) this;
        }

        public Criteria andGardenidNotEqualTo(Integer value) {
            addCriterion("gardenId <>", value, "gardenid");
            return (Criteria) this;
        }

        public Criteria andGardenidGreaterThan(Integer value) {
            addCriterion("gardenId >", value, "gardenid");
            return (Criteria) this;
        }

        public Criteria andGardenidGreaterThanOrEqualTo(Integer value) {
            addCriterion("gardenId >=", value, "gardenid");
            return (Criteria) this;
        }

        public Criteria andGardenidLessThan(Integer value) {
            addCriterion("gardenId <", value, "gardenid");
            return (Criteria) this;
        }

        public Criteria andGardenidLessThanOrEqualTo(Integer value) {
            addCriterion("gardenId <=", value, "gardenid");
            return (Criteria) this;
        }

        public Criteria andGardenidIn(List<Integer> values) {
            addCriterion("gardenId in", values, "gardenid");
            return (Criteria) this;
        }

        public Criteria andGardenidNotIn(List<Integer> values) {
            addCriterion("gardenId not in", values, "gardenid");
            return (Criteria) this;
        }

        public Criteria andGardenidBetween(Integer value1, Integer value2) {
            addCriterion("gardenId between", value1, value2, "gardenid");
            return (Criteria) this;
        }

        public Criteria andGardenidNotBetween(Integer value1, Integer value2) {
            addCriterion("gardenId not between", value1, value2, "gardenid");
            return (Criteria) this;
        }

        public Criteria andFreshidIsNull() {
            addCriterion("freshId is null");
            return (Criteria) this;
        }

        public Criteria andFreshidIsNotNull() {
            addCriterion("freshId is not null");
            return (Criteria) this;
        }

        public Criteria andFreshidEqualTo(Integer value) {
            addCriterion("freshId =", value, "freshid");
            return (Criteria) this;
        }

        public Criteria andFreshidNotEqualTo(Integer value) {
            addCriterion("freshId <>", value, "freshid");
            return (Criteria) this;
        }

        public Criteria andFreshidGreaterThan(Integer value) {
            addCriterion("freshId >", value, "freshid");
            return (Criteria) this;
        }

        public Criteria andFreshidGreaterThanOrEqualTo(Integer value) {
            addCriterion("freshId >=", value, "freshid");
            return (Criteria) this;
        }

        public Criteria andFreshidLessThan(Integer value) {
            addCriterion("freshId <", value, "freshid");
            return (Criteria) this;
        }

        public Criteria andFreshidLessThanOrEqualTo(Integer value) {
            addCriterion("freshId <=", value, "freshid");
            return (Criteria) this;
        }

        public Criteria andFreshidIn(List<Integer> values) {
            addCriterion("freshId in", values, "freshid");
            return (Criteria) this;
        }

        public Criteria andFreshidNotIn(List<Integer> values) {
            addCriterion("freshId not in", values, "freshid");
            return (Criteria) this;
        }

        public Criteria andFreshidBetween(Integer value1, Integer value2) {
            addCriterion("freshId between", value1, value2, "freshid");
            return (Criteria) this;
        }

        public Criteria andFreshidNotBetween(Integer value1, Integer value2) {
            addCriterion("freshId not between", value1, value2, "freshid");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Integer value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Integer value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Integer value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Integer value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Integer value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Integer> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Integer> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Integer value1, Integer value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andCreattimeIsNull() {
            addCriterion("creatTime is null");
            return (Criteria) this;
        }

        public Criteria andCreattimeIsNotNull() {
            addCriterion("creatTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreattimeEqualTo(Date value) {
            addCriterion("creatTime =", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeNotEqualTo(Date value) {
            addCriterion("creatTime <>", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeGreaterThan(Date value) {
            addCriterion("creatTime >", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeGreaterThanOrEqualTo(Date value) {
            addCriterion("creatTime >=", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeLessThan(Date value) {
            addCriterion("creatTime <", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeLessThanOrEqualTo(Date value) {
            addCriterion("creatTime <=", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeIn(List<Date> values) {
            addCriterion("creatTime in", values, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeNotIn(List<Date> values) {
            addCriterion("creatTime not in", values, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeBetween(Date value1, Date value2) {
            addCriterion("creatTime between", value1, value2, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeNotBetween(Date value1, Date value2) {
            addCriterion("creatTime not between", value1, value2, "creattime");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeIsNull() {
            addCriterion("preparedTime is null");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeIsNotNull() {
            addCriterion("preparedTime is not null");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeEqualTo(Date value) {
            addCriterion("preparedTime =", value, "preparedtime");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeNotEqualTo(Date value) {
            addCriterion("preparedTime <>", value, "preparedtime");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeGreaterThan(Date value) {
            addCriterion("preparedTime >", value, "preparedtime");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("preparedTime >=", value, "preparedtime");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeLessThan(Date value) {
            addCriterion("preparedTime <", value, "preparedtime");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeLessThanOrEqualTo(Date value) {
            addCriterion("preparedTime <=", value, "preparedtime");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeIn(List<Date> values) {
            addCriterion("preparedTime in", values, "preparedtime");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeNotIn(List<Date> values) {
            addCriterion("preparedTime not in", values, "preparedtime");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeBetween(Date value1, Date value2) {
            addCriterion("preparedTime between", value1, value2, "preparedtime");
            return (Criteria) this;
        }

        public Criteria andPreparedtimeNotBetween(Date value1, Date value2) {
            addCriterion("preparedTime not between", value1, value2, "preparedtime");
            return (Criteria) this;
        }

        public Criteria andGrowtimeIsNull() {
            addCriterion("growTime is null");
            return (Criteria) this;
        }

        public Criteria andGrowtimeIsNotNull() {
            addCriterion("growTime is not null");
            return (Criteria) this;
        }

        public Criteria andGrowtimeEqualTo(Date value) {
            addCriterion("growTime =", value, "growtime");
            return (Criteria) this;
        }

        public Criteria andGrowtimeNotEqualTo(Date value) {
            addCriterion("growTime <>", value, "growtime");
            return (Criteria) this;
        }

        public Criteria andGrowtimeGreaterThan(Date value) {
            addCriterion("growTime >", value, "growtime");
            return (Criteria) this;
        }

        public Criteria andGrowtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("growTime >=", value, "growtime");
            return (Criteria) this;
        }

        public Criteria andGrowtimeLessThan(Date value) {
            addCriterion("growTime <", value, "growtime");
            return (Criteria) this;
        }

        public Criteria andGrowtimeLessThanOrEqualTo(Date value) {
            addCriterion("growTime <=", value, "growtime");
            return (Criteria) this;
        }

        public Criteria andGrowtimeIn(List<Date> values) {
            addCriterion("growTime in", values, "growtime");
            return (Criteria) this;
        }

        public Criteria andGrowtimeNotIn(List<Date> values) {
            addCriterion("growTime not in", values, "growtime");
            return (Criteria) this;
        }

        public Criteria andGrowtimeBetween(Date value1, Date value2) {
            addCriterion("growTime between", value1, value2, "growtime");
            return (Criteria) this;
        }

        public Criteria andGrowtimeNotBetween(Date value1, Date value2) {
            addCriterion("growTime not between", value1, value2, "growtime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeIsNull() {
            addCriterion("collectTime is null");
            return (Criteria) this;
        }

        public Criteria andCollecttimeIsNotNull() {
            addCriterion("collectTime is not null");
            return (Criteria) this;
        }

        public Criteria andCollecttimeEqualTo(Date value) {
            addCriterion("collectTime =", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeNotEqualTo(Date value) {
            addCriterion("collectTime <>", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeGreaterThan(Date value) {
            addCriterion("collectTime >", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("collectTime >=", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeLessThan(Date value) {
            addCriterion("collectTime <", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeLessThanOrEqualTo(Date value) {
            addCriterion("collectTime <=", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeIn(List<Date> values) {
            addCriterion("collectTime in", values, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeNotIn(List<Date> values) {
            addCriterion("collectTime not in", values, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeBetween(Date value1, Date value2) {
            addCriterion("collectTime between", value1, value2, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeNotBetween(Date value1, Date value2) {
            addCriterion("collectTime not between", value1, value2, "collecttime");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeIsNull() {
            addCriterion("maturationTime is null");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeIsNotNull() {
            addCriterion("maturationTime is not null");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeEqualTo(Date value) {
            addCriterion("maturationTime =", value, "maturationtime");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeNotEqualTo(Date value) {
            addCriterion("maturationTime <>", value, "maturationtime");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeGreaterThan(Date value) {
            addCriterion("maturationTime >", value, "maturationtime");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("maturationTime >=", value, "maturationtime");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeLessThan(Date value) {
            addCriterion("maturationTime <", value, "maturationtime");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeLessThanOrEqualTo(Date value) {
            addCriterion("maturationTime <=", value, "maturationtime");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeIn(List<Date> values) {
            addCriterion("maturationTime in", values, "maturationtime");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeNotIn(List<Date> values) {
            addCriterion("maturationTime not in", values, "maturationtime");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeBetween(Date value1, Date value2) {
            addCriterion("maturationTime between", value1, value2, "maturationtime");
            return (Criteria) this;
        }

        public Criteria andMaturationtimeNotBetween(Date value1, Date value2) {
            addCriterion("maturationTime not between", value1, value2, "maturationtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table field
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 06 21:32:14 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}