package qile.garden.field.entity;

import java.util.Date;

public class Field {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.fieldName
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String fieldname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.length
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Double length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.width
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Double width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.gardenId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Integer gardenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.freshId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Integer freshid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.price
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.amount
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.creatTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.preparedTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Date preparedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.growTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Date growtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.collectTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Date collecttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.maturationTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Date maturationtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.id
     *
     * @return the value of field.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.id
     *
     * @param id the value for field.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.fieldName
     *
     * @return the value of field.fieldName
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getFieldname() {
        return fieldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.fieldName
     *
     * @param fieldname the value for field.fieldName
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setFieldname(String fieldname) {
        this.fieldname = fieldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.length
     *
     * @return the value of field.length
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Double getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.length
     *
     * @param length the value for field.length
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setLength(Double length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.width
     *
     * @return the value of field.width
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Double getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.width
     *
     * @param width the value for field.width
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setWidth(Double width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.gardenId
     *
     * @return the value of field.gardenId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Integer getGardenid() {
        return gardenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.gardenId
     *
     * @param gardenid the value for field.gardenId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setGardenid(Integer gardenid) {
        this.gardenid = gardenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.freshId
     *
     * @return the value of field.freshId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Integer getFreshid() {
        return freshid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.freshId
     *
     * @param freshid the value for field.freshId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setFreshid(Integer freshid) {
        this.freshid = freshid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.price
     *
     * @return the value of field.price
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.price
     *
     * @param price the value for field.price
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.amount
     *
     * @return the value of field.amount
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.amount
     *
     * @param amount the value for field.amount
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.creatTime
     *
     * @return the value of field.creatTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.creatTime
     *
     * @param creattime the value for field.creatTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.preparedTime
     *
     * @return the value of field.preparedTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Date getPreparedtime() {
        return preparedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.preparedTime
     *
     * @param preparedtime the value for field.preparedTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setPreparedtime(Date preparedtime) {
        this.preparedtime = preparedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.growTime
     *
     * @return the value of field.growTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Date getGrowtime() {
        return growtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.growTime
     *
     * @param growtime the value for field.growTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setGrowtime(Date growtime) {
        this.growtime = growtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.collectTime
     *
     * @return the value of field.collectTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Date getCollecttime() {
        return collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.collectTime
     *
     * @param collecttime the value for field.collectTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setCollecttime(Date collecttime) {
        this.collecttime = collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.maturationTime
     *
     * @return the value of field.maturationTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Date getMaturationtime() {
        return maturationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.maturationTime
     *
     * @param maturationtime the value for field.maturationTime
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setMaturationtime(Date maturationtime) {
        this.maturationtime = maturationtime;
    }
}