package qile.garden.field.entity;

public class Fresh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.name
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.origin
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.unitLength
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Double unitlength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.unitWidth
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Double unitwidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.growPeriod
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Integer growperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.description
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.id
     *
     * @return the value of fresh.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.id
     *
     * @param id the value for fresh.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.name
     *
     * @return the value of fresh.name
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.name
     *
     * @param name the value for fresh.name
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.origin
     *
     * @return the value of fresh.origin
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.origin
     *
     * @param origin the value for fresh.origin
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.unitLength
     *
     * @return the value of fresh.unitLength
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Double getUnitlength() {
        return unitlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.unitLength
     *
     * @param unitlength the value for fresh.unitLength
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setUnitlength(Double unitlength) {
        this.unitlength = unitlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.unitWidth
     *
     * @return the value of fresh.unitWidth
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Double getUnitwidth() {
        return unitwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.unitWidth
     *
     * @param unitwidth the value for fresh.unitWidth
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setUnitwidth(Double unitwidth) {
        this.unitwidth = unitwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.growPeriod
     *
     * @return the value of fresh.growPeriod
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Integer getGrowperiod() {
        return growperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.growPeriod
     *
     * @param growperiod the value for fresh.growPeriod
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setGrowperiod(Integer growperiod) {
        this.growperiod = growperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.description
     *
     * @return the value of fresh.description
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.description
     *
     * @param description the value for fresh.description
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}