package qile.garden.field.entity;

public class Grower {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.contact
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.tel
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.mail
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.settleType
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Integer settletype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.taxNo
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String taxno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.bankName
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String bankname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.bankAccount
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String bankaccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.id
     *
     * @return the value of grower.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.id
     *
     * @param id the value for grower.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.contact
     *
     * @return the value of grower.contact
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.contact
     *
     * @param contact the value for grower.contact
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.tel
     *
     * @return the value of grower.tel
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.tel
     *
     * @param tel the value for grower.tel
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.mail
     *
     * @return the value of grower.mail
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.mail
     *
     * @param mail the value for grower.mail
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.settleType
     *
     * @return the value of grower.settleType
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Integer getSettletype() {
        return settletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.settleType
     *
     * @param settletype the value for grower.settleType
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setSettletype(Integer settletype) {
        this.settletype = settletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.taxNo
     *
     * @return the value of grower.taxNo
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getTaxno() {
        return taxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.taxNo
     *
     * @param taxno the value for grower.taxNo
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setTaxno(String taxno) {
        this.taxno = taxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.bankName
     *
     * @return the value of grower.bankName
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.bankName
     *
     * @param bankname the value for grower.bankName
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.bankAccount
     *
     * @return the value of grower.bankAccount
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getBankaccount() {
        return bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.bankAccount
     *
     * @param bankaccount the value for grower.bankAccount
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount;
    }
}