package qile.garden.field.entity;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.wxUninId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Double wxuninid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.wxOpenId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private Double wxopenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.tel
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nickName
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.headPic
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    private String headpic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.wxUninId
     *
     * @return the value of member.wxUninId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Double getWxuninid() {
        return wxuninid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.wxUninId
     *
     * @param wxuninid the value for member.wxUninId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setWxuninid(Double wxuninid) {
        this.wxuninid = wxuninid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.wxOpenId
     *
     * @return the value of member.wxOpenId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public Double getWxopenid() {
        return wxopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.wxOpenId
     *
     * @param wxopenid the value for member.wxOpenId
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setWxopenid(Double wxopenid) {
        this.wxopenid = wxopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.tel
     *
     * @return the value of member.tel
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.tel
     *
     * @param tel the value for member.tel
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nickName
     *
     * @return the value of member.nickName
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nickName
     *
     * @param nickname the value for member.nickName
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.headPic
     *
     * @return the value of member.headPic
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public String getHeadpic() {
        return headpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.headPic
     *
     * @param headpic the value for member.headPic
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    public void setHeadpic(String headpic) {
        this.headpic = headpic;
    }
}