package qile.garden.grower.entity;

public class Grower {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.contact
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.tel
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.mail
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.settleType
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer settleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.taxNo
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String taxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.bankName
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grower.bankAccount
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String bankAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.id
     *
     * @return the value of grower.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.id
     *
     * @param id the value for grower.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.contact
     *
     * @return the value of grower.contact
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.contact
     *
     * @param contact the value for grower.contact
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.tel
     *
     * @return the value of grower.tel
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.tel
     *
     * @param tel the value for grower.tel
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.mail
     *
     * @return the value of grower.mail
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.mail
     *
     * @param mail the value for grower.mail
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.settleType
     *
     * @return the value of grower.settleType
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getSettleType() {
        return settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.settleType
     *
     * @param settleType the value for grower.settleType
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setSettleType(Integer settleType) {
        this.settleType = settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.taxNo
     *
     * @return the value of grower.taxNo
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getTaxNo() {
        return taxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.taxNo
     *
     * @param taxNo the value for grower.taxNo
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setTaxNo(String taxNo) {
        this.taxNo = taxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.bankName
     *
     * @return the value of grower.bankName
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.bankName
     *
     * @param bankName the value for grower.bankName
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grower.bankAccount
     *
     * @return the value of grower.bankAccount
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grower.bankAccount
     *
     * @param bankAccount the value for grower.bankAccount
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }
}