package qile.garden.garden.entity;

public class Garden {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garden.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garden.name
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garden.length
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Float length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garden.width
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Float width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garden.type
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garden.address
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garden.growerId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer growerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garden.longitude
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column garden.latitude
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Double latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garden.id
     *
     * @return the value of garden.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garden.id
     *
     * @param id the value for garden.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garden.name
     *
     * @return the value of garden.name
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garden.name
     *
     * @param name the value for garden.name
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garden.length
     *
     * @return the value of garden.length
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Float getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garden.length
     *
     * @param length the value for garden.length
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setLength(Float length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garden.width
     *
     * @return the value of garden.width
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Float getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garden.width
     *
     * @param width the value for garden.width
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setWidth(Float width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garden.type
     *
     * @return the value of garden.type
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garden.type
     *
     * @param type the value for garden.type
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garden.address
     *
     * @return the value of garden.address
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garden.address
     *
     * @param address the value for garden.address
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garden.growerId
     *
     * @return the value of garden.growerId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getGrowerId() {
        return growerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garden.growerId
     *
     * @param growerId the value for garden.growerId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setGrowerId(Integer growerId) {
        this.growerId = growerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garden.longitude
     *
     * @return the value of garden.longitude
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garden.longitude
     *
     * @param longitude the value for garden.longitude
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column garden.latitude
     *
     * @return the value of garden.latitude
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column garden.latitude
     *
     * @param latitude the value for garden.latitude
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
}