package qile.garden.fresh.entity;

public class Fresh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.name
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.origin
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.unitLength
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Double unitLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.unitWidth
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Double unitWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.growPeriod
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer growPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fresh.description
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.id
     *
     * @return the value of fresh.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.id
     *
     * @param id the value for fresh.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.name
     *
     * @return the value of fresh.name
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.name
     *
     * @param name the value for fresh.name
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.origin
     *
     * @return the value of fresh.origin
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.origin
     *
     * @param origin the value for fresh.origin
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.unitLength
     *
     * @return the value of fresh.unitLength
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Double getUnitLength() {
        return unitLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.unitLength
     *
     * @param unitLength the value for fresh.unitLength
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setUnitLength(Double unitLength) {
        this.unitLength = unitLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.unitWidth
     *
     * @return the value of fresh.unitWidth
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Double getUnitWidth() {
        return unitWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.unitWidth
     *
     * @param unitWidth the value for fresh.unitWidth
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setUnitWidth(Double unitWidth) {
        this.unitWidth = unitWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.growPeriod
     *
     * @return the value of fresh.growPeriod
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getGrowPeriod() {
        return growPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.growPeriod
     *
     * @param growPeriod the value for fresh.growPeriod
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setGrowPeriod(Integer growPeriod) {
        this.growPeriod = growPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fresh.description
     *
     * @return the value of fresh.description
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fresh.description
     *
     * @param description the value for fresh.description
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}