package qile.garden.garden.dao;

import qile.garden.garden.entity.Garden;

public interface GardenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    int insert(Garden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    int insertSelective(Garden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    Garden selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    int updateByPrimaryKeySelective(Garden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    int updateByPrimaryKey(Garden record);
}