package qile.garden.member.entity;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.wxUninId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Double wxUninId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.wxOpenId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private Double wxOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.tel
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nickName
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.headPic
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    private String headPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.wxUninId
     *
     * @return the value of member.wxUninId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Double getWxUninId() {
        return wxUninId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.wxUninId
     *
     * @param wxUninId the value for member.wxUninId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setWxUninId(Double wxUninId) {
        this.wxUninId = wxUninId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.wxOpenId
     *
     * @return the value of member.wxOpenId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public Double getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.wxOpenId
     *
     * @param wxOpenId the value for member.wxOpenId
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setWxOpenId(Double wxOpenId) {
        this.wxOpenId = wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.tel
     *
     * @return the value of member.tel
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.tel
     *
     * @param tel the value for member.tel
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nickName
     *
     * @return the value of member.nickName
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nickName
     *
     * @param nickName the value for member.nickName
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.headPic
     *
     * @return the value of member.headPic
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.headPic
     *
     * @param headPic the value for member.headPic
     *
     * @mbg.generated Thu Jun 07 06:46:14 CST 2018
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic;
    }
}