package qile.garden.field.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import qile.garden.field.entity.Field;
import qile.garden.field.entity.FieldExample;

public interface FieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    long countByExample(FieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int deleteByExample(FieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int insert(Field record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int insertSelective(Field record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    List<Field> selectByExample(FieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    Field selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Field record, @Param("example") FieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByExample(@Param("record") Field record, @Param("example") FieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByPrimaryKeySelective(Field record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByPrimaryKey(Field record);
}