package qile.garden.field.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import qile.garden.field.entity.Fresh;
import qile.garden.field.entity.FreshExample;

public interface FreshMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    long countByExample(FreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int deleteByExample(FreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int insert(Fresh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int insertSelective(Fresh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    List<Fresh> selectByExample(FreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    Fresh selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Fresh record, @Param("example") FreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByExample(@Param("record") Fresh record, @Param("example") FreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByPrimaryKeySelective(Fresh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fresh
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByPrimaryKey(Fresh record);
}