package qile.garden.field.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import qile.garden.field.entity.Garden;
import qile.garden.field.entity.GardenExample;

public interface GardenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    long countByExample(GardenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int deleteByExample(GardenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int insert(Garden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int insertSelective(Garden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    List<Garden> selectByExample(GardenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    Garden selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Garden record, @Param("example") GardenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByExample(@Param("record") Garden record, @Param("example") GardenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByPrimaryKeySelective(Garden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garden
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByPrimaryKey(Garden record);
}