package qile.garden.field.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import qile.garden.field.entity.Grower;
import qile.garden.field.entity.GrowerExample;

public interface GrowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    long countByExample(GrowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int deleteByExample(GrowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int insert(Grower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int insertSelective(Grower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    List<Grower> selectByExample(GrowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    Grower selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Grower record, @Param("example") GrowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByExample(@Param("record") Grower record, @Param("example") GrowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByPrimaryKeySelective(Grower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grower
     *
     * @mbg.generated Wed Jun 06 21:32:14 CST 2018
     */
    int updateByPrimaryKey(Grower record);
}